#!/bin/sh

# Pre-commit script to prevent merge markers from being committed.
# This simply searches the files that you are about to commit.

changed=$(git diff --cached --name-only --diff-filter=d)

if [ -z "$changed" ]; then
    exit 0
fi

echo "$changed" \
    | xargs -P0 perl -ne 'exit 1 if /^<{7}/ ... /^>{7}/ or (/^<{7}/ ... /^={7}/ and /^={7}/ ... /^>{7}/) or /^\|{7}/ or /^<{7}/ or /^>{7}/'

if [ "$?" -ne 0 ]; then
    echo "$changed" \
        | xargs -P0 grep -E '^[><=|]{7}' -HIn

    echo "[1;33mwarning:[0m Above files may contain conflict markers. Use [1m--no-verify[0m to bypass this check." 1>&2
    exit 1
fi
