#!/bin/sh

git --no-pager diff --cached --check
EC=$?

if [ $EC -ne 0 ]; then
    echo
    echo "[1;33mwarning:[0m Above files may contain conflict markers. Use [1m--no-verify[0m to bypass this check." 1>&2
fi

exit $EC
