#!/bin/sh

messages=$(git diff --cached --check)
EC=$?

if [ $EC -ne 0 ]; then
    warn1 "The following files may contain conflict markers or whitespace errors."
    warn2 "Pass [1m--no-verify[0m / [1m-n[0m to git-commit to bypass this check."
    echo
    echo "$messages"
fi

exit $EC
