nnoremap <buffer><silent> q :q<CR>
nnoremap <buffer><silent> o <CR>
nnoremap <buffer><silent> O <CR>:q<CR>
nnoremap <buffer><silent> <CR> <CR><C-w><C-p>
"nnoremap <buffer><silent> J :cnext<CR><C-w><C-p>
"nnoremap <buffer><silent> K :cprev<CR><C-w><C-p>
nnoremap <buffer><silent> J j<CR><C-w><C-p>
nnoremap <buffer><silent> K k<CR><C-w><C-p>
nnoremap <buffer><silent> <leader><CR> <C-w><CR><C-w>L
