#!/usr/bin/env bash

set -o errexit -o pipefail
shopt -s nullglob
readonly argv0=clean
readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

# default options (enabled)
all=1

# default options (disabled)
sync=0 manual=0

usage() {
    plain "usage: $argv0 [-asm] [long options]"
    exit 1
}

source /usr/share/makepkg/util/util.sh
source /usr/share/makepkg/util/message.sh

if [[ -t 2 && ! -o xtrace ]]; then
    colorize
fi

if getopt -T || (($? != 4)); then
    error "$argv0: util-linux getopt required"
    exit 22
fi

longopts=all,sync,manual
shortopts=asm

if optstring=$(getopt -o "$shortopts" -l "$longopts" -n "$argv0" -- "$@"); then
    eval set -- "$optstring"
else
    usage
fi

unset root repo
while true; do
    case "$1" in
        -a|--all)
            all=1
            shift ;;
        -s|--sync)
            all=0
            sync=1
            shift ;;
        -m|--manual)
            all=0
            manual=1
            shift;;
        *)
            shift
            break ;;
    esac
done

if ((all)); then
    sync=1 manual=1
fi

if ((sync)); then
    rm "$AURDEST/*/*.log"
fi

if ((manual)); then
    manual_dir="$HOME/packages"
    rm "$manual_dir/*/*.log"
fi

# vim: set et sw=4 sts=4 ft=sh:
