#!/usr/bin/env bash
# aur-remove - remove packages from repository
[[ -v AUR_DEBUG ]] && set -o xtrace
set -o errexit
shopt -s extglob
argv0=remove
PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

# default arguments
db_name=${db_name:-$AUR_REPO}
repo_args=()

usage() {
    plain >&2 'usage: %s [-dam] [--] pkgname...' "$argv0"
    exit 1
}

source /usr/share/makepkg/util/util.sh
source /usr/share/makepkg/util/message.sh
source /usr/share/makepkg/util/parseopts.sh

if [[ ! -v NO_COLOR ]] && [[ ! -v AUR_DEBUG ]]; then
    [[ -t 2 ]] && colorize
fi

# mollyguard for makepkg
if (( UID == 0 )) && [[ ! -v AUR_ASROOT ]]; then
    warning 'aur-%s is not meant to be run as root.' "$argv0"
    warning 'To proceed anyway, set the %s variable.' 'AUR_ASROOT'
    exit 1
fi

opt_short='d:ma'
opt_long=('database:' 'root:' 'manual' 'aur')

if ! parseopts "$opt_short" "${opt_long[@]}" -- "$@"; then
    usage
fi
set -- "${OPTRET[@]}"

while true; do
    case "$1" in
        -d|--database) shift; db_name=$1 ;;
        -m|--manual)   db_name=manual ;;
        -a|--aur)      db_name=aur ;;
        --root)        shift; repo_args+=(--root "$1") ;;
        --)            shift; break ;;
    esac
    shift
done

repo_args+=(-d "$db_name")
repo_path=$(aur repo "${repo_args[@]}" --path-list | grep "/$db_name/")

if [[ -w $repo_path ]]; then
    msg "Using [$db_name] repository" >&2
else
    error "$argv0: $repo_path: permission denied"
    exit 13
fi

repo-remove "$repo_path" "$@"
paccache -c "${repo_path%/*}" -rvk0 "$@"

# vim: set et sw=4 sts=4 ft=sh:
