#!/usr/bin/env bash
# aur-get - download and build AUR packages automatically
set -o errexit -o pipefail
readonly argv0=get
readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

for arg in "$@"; do
    case $arg in
        -) cat ;;
        *) printf '%s\n' "$arg" ;;
    esac
done | xargs aur sync \
    -cfd aur \
    -C /etc/pacman.conf \
    -M /home/amairya/.config/pacman/makepkg.conf

# vim: set et sw=4 sts=4 ft=sh:
