#!/usr/bin/env bash
# aur-remove - remove packages from repository
set -o errexit -o pipefail
shopt -s nullglob
shopt -s extglob
readonly argv0=remove
readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

# default arguments
repo=${repo:-$AUR_REPO}
repo_args=()

usage() {
    plain "usage: $argv0 [-dam] [--] pkgname... [-]"
    exit 1
}

source /usr/share/makepkg/util/util.sh
source /usr/share/makepkg/util/message.sh
source /usr/share/makepkg/util/parseopts.sh

if [[ -t 2 && ! -o xtrace ]]; then
    colorize
fi

opt_short='d:ma'
opt_long=('repo:' 'database:' 'root:' 'manual' 'aur')

if ! parseopts "$opt_short" "${opt_long[@]}" -- "$@"; then
    usage
fi
set -- "${OPTRET[@]}"

while true; do
    case "$1" in
        -d|--database|--repo) shift; repo=$1 ;;
        -m|--manual)          repo=manual ;;
        -a|--aur)             repo=aur ;;
        --root)               shift; repo_args+=(--root "$1") ;;
        --)                   shift; break ;;
    esac
    shift
done
unset opt_short opt_long OPTRET

repo_args+=(-d "$repo")
repo_path=$(aur repo "${repo_args[@]}")

if [[ -w $repo_path ]]; then
    msg "Using [$repo] repository" >&2
else
    error "$argv0: $repo_path: permission denied"
    exit 13
fi

for arg in "$@"; do
    case $arg in
        -) cat ;;
        *) printf '%s\n' "$arg" ;;
    esac
done | xargs -r repo-remove "$repo_path.tar"

# vim: set et sw=4 sts=4 ft=sh:
