#!/usr/bin/env bash
# aur-manual - build AUR packages manually
set -o errexit -o pipefail
shopt -s nullglob
shopt -s extglob
readonly argv0=manual
readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

aur build \
    -cfd manual \
    "$@" \
    -C /etc/pacman.conf \
    -M ~/.config/pacman/makepkg.conf

# vim: set et sw=4 sts=4 ft=sh:
