#!/usr/bin/env bash
# aur-clean - remove cache
set -o errexit -o pipefail
shopt -s nullglob
shopt -s extglob
readonly argv0=clean
readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

# default options (enabled)
all=1

# default options (disabled)
sync=0 manual=0

usage() {
    plain "usage: $argv0 [-asm] [long options]"
    exit 1
}

source /usr/share/makepkg/util/util.sh
source /usr/share/makepkg/util/message.sh
source /usr/share/makepkg/util/parseopts.sh

if [[ -t 2 && ! -o xtrace ]]; then
    colorize
fi

opt_short='asm'
opt_long=('all' 'sync' 'manual')

if ! parseopts "$opt_short" "${opt_long[@]}" -- "$@"; then
    usage
fi
set -- "${OPTRET[@]}"

unset root repo
while true; do
    case "$1" in
        -a|--all)    all=1 ;;
        -s|--sync)   all=0; sync=1 ;;
        -m|--manual) all=0; manual=1 ;;
        --)          shift; break ;;
    esac
    shift
done
unset opt_short opt_long OPTRET

if ((all)); then
    sync=1 manual=1
fi

if ((sync)); then
    rm "$AURDEST"/*/*.log
fi

if ((manual)); then
    manual_dir="$HOME/packages"
    rm "$manual_dir"/*/*.log
fi

# vim: set et sw=4 sts=4 ft=sh:
