#!/usr/bin/env bash

# sync VCS packages that are outdated according to aur-vercmp-devel
# sync all packages that are outdated according to AurJson (--upgrades)
aur vercmp-devel "$@" | cut -d: -f1 | xargs -r aur sync --no-ver-shallow --upgrades "$@"
