#!/usr/bin/env bash
# aur-manual - build AUR packages manually
set -o errexit -o pipefail
readonly argv0=manual
readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

aur build \
    -cfd manual \
    -C /etc/pacman.conf \
    -M "$HOME"/.config/pacman/makepkg.conf \
    "$@"

awesome-client 'require("config.brokers").pacman:update()'

# vim: set et sw=4 sts=4 ft=sh:
