#!/usr/bin/env bash
# aur-clean - remove cache
set -o errexit -o pipefail
shopt -s nullglob
shopt -s extglob
readonly argv0=clean
readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

# default options (disabled)
all=0 aur=0 manual=0

usage() {
    plain "usage: $argv0 [-Aam] [long options]"
    exit 1
}

source /usr/share/makepkg/util/util.sh
source /usr/share/makepkg/util/message.sh
source /usr/share/makepkg/util/parseopts.sh

if [[ -t 2 && ! -o xtrace ]]; then
    colorize
fi

opt_short='Aam'
opt_long=('all' 'aur' 'manual')

if ! parseopts "$opt_short" "${opt_long[@]}" -- "$@"; then
    usage
fi
set -- "${OPTRET[@]}"

while true; do
    case "$1" in
        -A|--all)    all=1 ;;
        -a|--aur)    all=0; aur=1 ;;
        -m|--manual) all=0; manual=1 ;;
        --)          shift; break ;;
    esac
    shift
done
unset opt_short opt_long OPTRET

if ((all)); then
    aur=1 manual=1
fi

if ((aur)); then
    rm "$AURDEST"/*/*.log
fi

if ((manual)); then
    rm "$HOME/packages"/*/*.log
fi

# vim: set et sw=4 sts=4 ft=sh:
