#!/usr/bin/env bash

mount='0'

readonly argv0="$0"

usage() {
  echo "usage: $argv0 [-u]"
  exit 1
}

while getopts u OPT; do
  case $OPT in
    u) mount='1' ;;
    *) usage ;;
  esac
done
shift $((OPTIND - 1))
OPTIND=1

readonly mount

if [[ "$mount" -eq "0" ]]; then
  mountpoint -q /var/lib/aurbuild \
    && echo 'Already mounted.' \
    && exit 1 \
    || sudo mount /var/lib/aurbuild
else
  mountpoint -q /var/lib/aurbuild \
    && sudo umount /var/lib/aurbuild
fi
