#!/usr/bin/env zsh

readonly cmd=$1
shift

case $cmd in

    vim)
        vim \
            ~/.vimrc \
            ~/.vim/after/**/* \
            "$@"
        ;;

    tmux)
        vim \
            ~/.tmux.conf \
            ~/.tmux.minimal.conf \
            "$@"
        ;;

    git)
        vim \
            ~/.gitconfig \
            ~/.gitignore \
            ~/.gitmodules \
            ~/.config/git/hooks/**/* \
            "$@"
        ;;

    zsh)
        vim \
            ~/.zshrc \
            ~/.config/zsh/* \
            ~/.zprofile \
            ~/.profile \
            "$@"
        ;;

    bash)
        vim \
            ~/.bashrc \
            ~/.config/bash/* \
            ~/.bash_profile \
            ~/.profile \
            "$@"
        ;;

    aw)
        vim \
            ~/.config/awesome/rc.lua \
            ~/.config/awesome/themes/blackout/theme.lua \
            ~/.config/awesome/config/* \
            "$@"
        ;;

    xorg)
        vim \
            ~/.xinitrc \
            "$@"
        ;;

    bin)
        vim \
            ~/.bin/* \
            "$@"
        ;;

    *)
        vim ~/.bin/conf \
            "$0"
        ;;

esac
