#!/usr/bin/env bash

cmd=$1
shift

case $cmd in
    vim)
        vim \
            ~/.vimrc \
            "$@"
        ;;
    tmux)
        vim \
            ~/.tmux.conf \
            ~/.tmux.minimal.conf \
            "$@"
        ;;
    git)
        vim \
            ~/.gitconfig \
            ~/.gitignore \
            ~/.gitmodules \
            "$@"
        ;;
    zsh)
        vim \
            ~/.zshrc \
            ~/.zsh.d/*.zsh \
            ~/.zprofile \
            ~/.profile \
            ~/.oh-my-zsh/themes/agnoster-custom.zsh-theme \
            "$@"
        ;;
    bash)
        vim \
            ~/.bashrc \
            ~/.bash_profile \
            ~/.profile \
            "$@"
        ;;
    aw)
        vim \
            ~/.config/awesome/rc.lua \
            ~/.config/awesome/themes/blackout/theme.lua \
            "$@"
        ;;
    xorg)
        vim \
            ~/.xinitrc \
            "$@"
        ;;
    bin)
        vim \
            ~/.bin/* \
            "$@"
        ;;
    *)
        vim \
            "$0"
        ;;
esac
