#!/usr/bin/env bash

file=$(mktemp --suffix=.md)
trap 'rm -f "$file"' SIGINT SIGTERM EXIT

vim --nofork "$file"
EC=$?

if [[ $EC == '0' ]]; then
    nohup xclip -i -selection clipboard -rmlastnl "$file" > /dev/null 2>&1
fi

exit $EC
