#!/usr/bin/env bash

fzf() {
    fzf-tmux -d 50% -- "$@"
}

# print git commit sha-hash

if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
    exit 1
fi

git log --pretty=lo --color --date=human "$@" \
    | fzf +s -m +e --ansi --reverse --tiebreak=index \
    | grep -o '[a-f0-9]\{7,\}'
