#!/usr/bin/env zsh

alias fzf='fzf-tmux -d 30%'

# checkout git branch/tag

if ! $(git rev-parse --is-inside-work-tree >/dev/null 2>&1); then
  exit 1
fi

tags=$(git tag | awk '{print "\x1b[31;1mtag\x1b[m\t" $1}') \
  || exit 1

branches=$(git branch --all | grep -v HEAD \
  | sed 's/.* //' | sed 's#remotes/[^/]*/##' | sort -u \
  | awk '{print "\x1b[34;1mbranch\x1b[m\t" $1}') \
  || exit 1

target=$(echo "$tags\\n$branches" \
  | fzf -- +s +m -e --ansi --tac -d '\t' -n 2) \
  || exit 1

git checkout $(echo "$target" | awk '{print $2}')
