#!/usr/bin/env bash

fzf() {
    fzf-tmux -d 30% -- "$@"
}

# git commit browser

if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
    exit 1
fi

ctrl_m="echo {} \
    | grep -o '[a-f0-9]\\{7,\\}' \
    | xargs git show --color=always"

git log --pretty=lo --graph --color --date=human "$@" \
    | fzf +s +m +e --ansi --reverse --tiebreak=index \
    --bind "ctrl-s:toggle-sort" \
    --bind "ctrl-m:execute:(${ctrl_m})"
