#!/usr/bin/env bash

line=$(printf %"$(tput cols)"s | sed 's/ /─/g')
export line

git-one() {
    path=$1
    shift

    if ! git -C "$path" rev-parse --is-inside-work-tree > /dev/null 2>&1; then
        echo "[1;91mError:[0m $path is not a Git repository." 1>&2
        return 1
    fi

    printf '%s\n%s\n%s' \
        "$(git -C "$path" "$@" 2>&1 | awk 'NF')" \
        "Done: [1m$path[0m" \
        "$line"
}
export -f git-one

find . -mindepth 1 -maxdepth 1 -type d \
    | xargs -r -I@ -P0 bash -c "git-one @ $*"
