#!/usr/bin/env bash

fzf() {
    fzf-tmux -d 80% -- "$@"
}

# git commit browser

if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
    exit 1
fi

while out=$(
    git log --pretty=lo --graph --color --date=human "$@" \
        | fzf +s +m +e --ansi -q "$q" --reverse --tiebreak=index \
        --print-query --expect=ctrl-m,ctrl-l);
do
    mapfile -t out <<< "$out"
    q="${out[0]}"
    k="${out[1]}"
    sha="$(grep -o '[a-f0-9]\{7,\}' <<< "${out[-1]}")"
    [[ -z "$sha" ]] && continue

    if [[ "$k" == 'ctrl-m' ]]; then
        git show --pretty=lf --stat --summary --patch "$sha" --
    elif [[ "$k" == 'ctrl-l' ]]; then
        git log --pretty=lt --graph --color --date=human "$sha" --
    else
        git show --pretty=lf --stat --summary --patch "$sha" --
    fi
done
