#!/usr/bin/env bash

# separator
sep=$(echo 2B | xxd -r -p)

git config --get-regexp 'alias\.' \
    | cut -c 7- \
    | sed -e "s/^/[1m/" -e "s/ /[0m${sep}/" \
    | column -t -s "${sep}" \
    | sort \
    | less -SR
