#!/usr/bin/env bash

dir="$(pwd)"
dir="${1:-$dir}"

read -r -p "[1;97mInstall ditfiles at [1;91m${dir}[1;97m? [yN] [0m" reply
echo

if [[ ! $reply =~ ^[Yy]$ ]]; then
    echo 'Aborted.'
    exit
fi

# Highlighting for output
highlight() {
    echo "[1;34m::[0m [1m$*[0m"
}

# Install oh-my-zsh (doing this after cloning dotfiles will result in conflicts)
highlight 'Clone gh://robbyrussell/oh-my-zsh'
git clone 'https://github.com/robbyrussell/oh-my-zsh' \
    "$dir/.oh-my-zsh"

# Download and temporarily install dotfiles.sh
if [[ -f $HOME/projects/dotfiles.sh/dotfiles ]]; then
    highlight 'Use ~/projects/dotfiles.sh/dotfiles'
else
    highlight 'Clone gh://alfunx/dotfiles.sh'
    mkdir "$HOME/projects"
    git clone 'https://github.com/alfunx/dotfiles.sh' \
        "$HOME/projects/dotfiles.sh"
fi
dotfiles="$HOME/projects/dotfiles.sh/dotfiles"

# Clone dotfiles repo
highlight 'Clone gh://alfunx/.dotfiles'
$dotfiles clone 'https://github.com/alfunx/.dotfiles' \
    "$dir/.dotfiles"

# Load submodules
highlight 'Initialize submodules'
$dotfiles submodule update --init --recursive

# Setup xdg directories
highlight 'Setup directories'
$dir/.bin/setup-dirs

# Setup links
highlight 'Setup sym-links'
$dir/.bin/setup-links

# Further informations (instructions for manual steps)
highlight 'Install root-scripts with: ./.bin/setup-root-scripts'
