#!/usr/bin/env bash

git clone https://github.com/robbyrussell/oh-my-zsh \
  "$HOME/.oh-my-zsh"
git clone https://github.com/zsh-users/zsh-syntax-highlighting \
  "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
git clone https://github.com/zsh-users/zsh-completions \
  "$HOME/.oh-my-zsh/custom/plugins/zsh-completions"
