#!/usr/bin/env bash

pictures_dir="$(xdg-user-dir PICTURES 2> /dev/null)"
lock="${pictures_dir:-$HOME/Pictures}/lock.png"
image=$(mktemp --suffix=.png)
trap 'rm -f "$image"' SIGINT SIGTERM EXIT

maim -u \
    | convert png:- -scale 10% -scale 1000% \
    "$lock" -gravity center -composite -matte "$image"

i3lock \
    --image="$image" \
    --insidecolor=EBDBB233 \
    --insidevercolor=FABD2FFF \
    --insidewrongcolor=FB4934FF \
    --ringcolor=282828FF \
    --ringvercolor=282828FF \
    --ringwrongcolor=282828FF \
    --linecolor=EBDBB2FF \
    --keyhlcolor=EBDBB2FF \
    --bshlcolor=FB4934FF \
    --separatorcolor=282828FF \
    --timecolor=EBDBB2FF \
    --datecolor=00000000 \
    --layoutcolor=00000000 \
    --indpos='x+100:y+720' \
    --timepos='x+210:y+732' \
    --timestr='%H:%M' \
    --time-font='Iosevka Custom' \
    --force-clock \
    --refresh-rate=30 \
    --radius=32 \
    --ring-width=4 \
    --veriftext='' \
    --wrongtext='' \
    --noinputtext='' \
    --ignore-empty-password
