#!/usr/bin/env bash

pictures_dir="$(xdg-user-dir PICTURES 2> /dev/null)"
output_dir="${pictures_dir:-$HOME/Pictures}/screenshots"
output_file="$output_dir/$(date +%Y-%m-%d_%T).png"

readonly argv0="$0"
declare -i hide_cursor=0 select_area=0

usage() {
    echo "usage: $argv0 [-hs] [-o output-file]"
    exit 1
}

while getopts hso: OPT; do
    case $OPT in
        h) hide_cursor=1 ;;
        s) select_area=1 ;;
        o) output_file=$OPTARG ;;
        *) usage ;;
    esac
done
shift $((OPTIND - 1))
OPTIND=1

readonly hide_cursor select_area output_file

maim_flags=

if ((hide_cursor)); then
    maim_flags="$maim_flags -u"
fi

if ((select_area)); then
    maim_flags="$maim_flags -s -b 3 -c 0.98431372549019607843,0.28627450980392156862,0.20392156862745098039,1"
fi

# We want word splitting here
if maim $maim_flags "$output_file"; then
    notify-send \
        --expire-time=10000 \
        --icon="$output_file" \
        'Screenshot' \
        "Saved as $(basename "$output_file")\\nunder $("$HOME/.bin/show-short-dir" "$output_dir")"
fi
