#!/usr/bin/env bash

pacman-date-log() {
    { /usr/bin/pacman "${1:--Qeq}"; cat /var/log/pacman.log; } | awk '
        NF == 1 { pkgs[$0] = 1; }
        $4 == "installed" {
            if ($5 in pkgs) { pkgs[$5] = $1 " " $2; }
        }
        END {
            for (p in pkgs) { print pkgs[p], p; }
        }' | sort
}

update-widget() {
    if [[ -n "$SUDO_USER" ]]; then
        runuser -u "$SUDO_USER" -- \
            update-pacman-widget
    else
        update-pacman-widget
    fi
}

update-widget

if [[ $1 == '--log' ]]; then
    shift
    pacman-date-log "$@"
else
    /usr/bin/pacman "$@"
fi

update-widget
