#!/usr/bin/env bash

choice_by_rofi() {
    output=(
        '0: Lock'
        '1: Suspend'
        '2: Logout'
        '3: Reboot'
        '4: Poweroff'
    )

    choice=$(printf '%s\n' "${output[@]}" \
        | rofi -i -lines 5 -dmenu -p 'session' \
        | cut -d ':' -f 1)
}

[[ -z "$DISPLAY" ]] && exit 1

choice_by_rofi

[[ -z "$choice" ]] && exit 1

case "$choice" in
    0) ~/.bin/lock & ;;
    1) systemctl suspend & ;;
    2) systemctl kill "$(pgrep X)" & ;;
    3) systemctl reboot & ;;
    4) systemctl poweroff & ;;
esac
