#!/usr/bin/env bash

choice_by_rofi() {
    choice=$(echo -e "1: Lock\\n2: Suspend\\n3: Logout\\n4: Reboot\\n5: Poweroff" \
        | rofi -i -lines 5 -dmenu -p 'session' \
        | cut -d ':' -f 1)
}

[[ -z "$DISPLAY" ]] && exit 1

choice_by_rofi
sleep 0.5

[[ -z "$choice" ]] && exit 1

case "$choice" in
    1) ~/.bin/lock & ;;
    2) systemctl suspend & ;;
    3) kill -9 -1 & ;;
    4) systemctl reboot & ;;
    5) systemctl poweroff & ;;
esac
