#!/usr/bin/env bash

sudo cp -f "$HOME/.bin/lock" '/usr/local/bin/custom-lockscreen'
sudo cp -f "$HOME/.bin/update-pkglist" '/usr/local/bin/update-pkglist'
sudo cp -f "$HOME/.bin/aurremove" '/usr/local/bin/aurremove'
sudo cp -f "$HOME/.bin/aurupdate" '/usr/local/bin/aurupdate'
sudo cp -f "$HOME/.bin/edit-in-vim" '/usr/local/bin/edit-in-vim'
