#!/usr/bin/env bash

ln -fs "$HOME/.config/awesome/themes/blackout/wallpapers/wall.png" "$HOME/pictures/wall.png"
ln -fs "$HOME/.config/awesome/themes/blackout/wallpapers/lock.png" "$HOME/pictures/lock.png"
ln -fs "$HOME/projects/gdb-dashboard/.gdbinit" "$HOME/.gdbinit"
