#!/usr/bin/env bash

readonly argv0="$0"
# readonly url='https://api.ipify.org'
readonly url='https://ip.mariya.ch'
declare -i full=0

usage() {
    echo "usage: $argv0 [-f]"
    exit 1
}

while getopts f OPT; do
    case $OPT in
        f) full=1 ;;
        *) usage ;;
    esac
done
shift $((OPTIND - 1))
OPTIND=1

if ((full)); then
    echo "SSID:     $(netctl-auto list | grep -Po '\* wlp58s0-\K.*')"
    echo "Internal: $(ip address show wlp58s0 | grep -Po 'inet \K[\d.]+')"
    echo "External: $(curl -s "$url")"
else
    echo "SSID:     $(netctl-auto list | grep -Po '\* wlp58s0-\K.*')"
    echo "Internal: $(ip address show wlp58s0 | grep -Po 'inet \K[\d.]+')"
fi
