#!/usr/bin/env bash

usage() {
	cat <<- _EOF_
		Usage: show-colors [-h|--help] <COMMAND>
		Print, and convert from and to hex colors.

		OPTIONS
		    -h, --help      Show this usage message

		CUSTOM COMMANDS
		    all             Print all 255 colors enumerated (dec)
		    all-dec         Print all 255 colors and according hex values
		    to-hex          Convert color from dec to hex
		    from-hex        Convert color from hex to dec
_EOF_
}


print-colors(){
    for c; do
        printf '\e[48;5;%dm%03d' $c $c
    done
    printf '\e[0m \n'
}

all() {
    IFS=$' \t\n'
    print-colors {0..15}
    for ((i=0;i<6;i++)); do
        print-colors $(seq $((i*36+16)) $((i*36+51)))
    done
    print-colors {232..255}
}

from-hex(){
    hex=${1#"#"}
    r=$(printf '0x%0.2s' ${hex})
    g=$(printf '0x%0.2s' ${hex#??})
    b=$(printf '0x%0.2s' ${hex#????})
    printf 'dec: %03d\n' "$(( (r<75?0:(r-35)/40)*6*6 + 
                              (g<75?0:(g-35)/40)*6     +
                              (b<75?0:(b-35)/40)       + 16 ))"
}

to-hex(){
    dec=$(($1%256))     ### input must be a number in range 0-255.
    if [ "$dec" -lt "16" ]; then
        bas=$(( dec%16 ))
        mul=128
        [ "$bas" -eq "7" ] && mul=192
        [ "$bas" -eq "8" ] && bas=7
        [ "$bas" -gt "8" ] && mul=255
        a="$((  (bas&1)      *mul ))"
        b="$(( ((bas&2)>>1)*mul ))" 
        c="$(( ((bas&4)>>2)*mul ))"
        printf 'dec: %3s, basic: #%02x%02x%02x\n' "$dec" "$a" "$b" "$c"
    elif [ "$dec" -gt 15 ] && [ "$dec" -lt 232 ]; then
        b=$(( (dec-16)%6    )); b=$(( b==0?0: b*40 + 55 ))
        g=$(( (dec-16)/6%6)); g=$(( g==0?0: g*40 + 55 ))
        r=$(( (dec-16)/36 )); r=$(( r==0?0: r*40 + 55 ))
        printf 'dec: %3s, color: #%02x%02x%02x\n' "$dec" "$r" "$g" "$b"
    else
        gray=$(( (dec-232)*10+8 ))
        printf 'dec: %3s, gray: #%02x%02x%02x\n' "$dec" "$gray" "$gray" "$gray"
    fi
}

all-dec() {
    for i in $(seq 0 255); do
        to-hex ${i}
    done
}

# Main

color_cmd="$1"
shift

case $color_cmd in
    -h|--help|help)
        usage
        exit
        ;;
    all)
        all
        ;;
    all-dec|alldex|dec)
        all-dec
        ;;
    from-hex|fromhex|from)
        from-hex "$@"
        ;;
    to-hex|tohex|to)
        to-hex "$@"
        ;;
    *)
        all
esac
