#!/usr/bin/env bash

echo "SSID: $(netctl-auto list | grep -Po '\* wlp58s0-\K.*')
Internal: $(ip address show wlp58s0 | grep -Po 'inet \K[\d.]+')
External: $(wget https://api.ipify.org -O - -q)" \
    | column -t
