#!/usr/bin/env bash

usage() {
	cat <<- _EOF_
		Usage: show-colors [-h|--help] <COMMAND>
		Print, and convert from and to hex colors.

		OPTIONS
		    -h, --help      Show this usage message

		CUSTOM COMMANDS
		    all             Print all 255 colors enumerated (dec)
		    all-dec         Print all 255 colors and according hex values
		    to-hex          Convert color from dec to hex
		    from-hex        Convert color from hex to dec
		    gruvbox         Show gruvbox colors
_EOF_
}

print-colors(){
    for c; do
        printf '\e[48;5;%dm%03d' $c $c
    done
    printf '\e[0m \n'
}

all() {
    IFS=$' \t\n'
    print-colors {0..15}
    for ((i=0;i<6;i++)); do
        print-colors $(seq $((i*36+16)) $((i*36+51)))
    done
    print-colors {232..255}
}

from-hex(){
    hex=${1#"#"}
    r=$(printf '0x%0.2s' ${hex})
    g=$(printf '0x%0.2s' ${hex#??})
    b=$(printf '0x%0.2s' ${hex#????})
    printf 'dec: %03d\n' "$(( (r<75?0:(r-35)/40)*6*6 + 
                              (g<75?0:(g-35)/40)*6     +
                              (b<75?0:(b-35)/40)       + 16 ))"
}

to-hex(){
    dec=$(($1%256))     ### input must be a number in range 0-255.
    if [ "$dec" -lt "16" ]; then
        bas=$(( dec%16 ))
        mul=128
        [ "$bas" -eq "7" ] && mul=192
        [ "$bas" -eq "8" ] && bas=7
        [ "$bas" -gt "8" ] && mul=255
        a="$((  (bas&1)      *mul ))"
        b="$(( ((bas&2)>>1)*mul ))" 
        c="$(( ((bas&4)>>2)*mul ))"
        printf 'dec: %3s, basic: #%02x%02x%02x\n' "$dec" "$a" "$b" "$c"
    elif [ "$dec" -gt 15 ] && [ "$dec" -lt 232 ]; then
        b=$(( (dec-16)%6    )); b=$(( b==0?0: b*40 + 55 ))
        g=$(( (dec-16)/6%6)); g=$(( g==0?0: g*40 + 55 ))
        r=$(( (dec-16)/36 )); r=$(( r==0?0: r*40 + 55 ))
        printf 'dec: %3s, color: #%02x%02x%02x\n' "$dec" "$r" "$g" "$b"
    else
        gray=$(( (dec-232)*10+8 ))
        printf 'dec: %3s, gray: #%02x%02x%02x\n' "$dec" "$gray" "$gray" "$gray"
    fi
}

all-dec() {
    for i in $(seq 0 255); do
        to-hex ${i}
    done
}

gruvbox() {
    echo -n          "bg       #282828   235    0   $(print-colors   0)"
    echo "            bg0_h    #1d2021   234    0   $(print-colors 234)"
    echo -n          "red      #cc241d   124    1   $(print-colors   1)"
    echo "            bg0      #282828   235    0   $(print-colors 235)"
    echo -n          "green    #98971a   106    2   $(print-colors   2)"
    echo "            bg0_s    #32302f   236    0   $(print-colors 236)"
    echo -n          "yellow   #d79921   172    3   $(print-colors   3)"
    echo "            bg1      #3c3836   237    -   $(print-colors 237)"
    echo -n          "blue     #458588    66    4   $(print-colors   4)"
    echo "            bg2      #504945   239    -   $(print-colors 239)"
    echo -n          "purple   #b16286   132    5   $(print-colors   5)"
    echo "            bg3      #665c54   241    -   $(print-colors 241)"
    echo -n          "aqua     #689d6a    72    6   $(print-colors   6)"
    echo "            bg4      #7c6f64   243    -   $(print-colors 243)"
    echo -n          "gray     #a89984   246    7   $(print-colors   7)"
    echo "            gray     #928374   245    8   $(print-colors 245)"
    echo -n          "gray     #928374   245    8   $(print-colors   8)"
    echo "            fg4      #a89984   246    7   $(print-colors 246)"
    echo -n          "red      #fb4934   167    9   $(print-colors   9)"
    echo "            fg3      #bdae93   248    -   $(print-colors 248)"
    echo -n          "green    #b8bb26   142   10   $(print-colors  10)"
    echo "            fg2      #d5c4a1   250    -   $(print-colors 250)"
    echo -n          "yellow   #fabd2f   214   11   $(print-colors  11)"
    echo "            fg1      #ebdbb2   223   15   $(print-colors 223)"
    echo -n          "blue     #83a598   109   12   $(print-colors  12)"
    echo "            fg0      #fbf1c7   229    -   $(print-colors 229)"
    echo -n          "purple   #d3869b   175   13   $(print-colors  13)"
    echo "            orange   #d65d0e   166    -   $(print-colors 166)"
    echo -n          "aqua     #8ec07c   108   14   $(print-colors  14)"
    echo "            orange   #fe8019   208    -   $(print-colors 208)"
    echo             "fg       #ebdbb2   223   15   $(print-colors  15)" 
}

# Main

color_cmd="$1"
shift

case $color_cmd in
    -h|--help|help)
        usage
        exit
        ;;
    all)
        all
        ;;
    all-dec|alldex|dec)
        all-dec
        ;;
    from-hex|fromhex|from)
        from-hex "$@"
        ;;
    to-hex|tohex|to)
        to-hex "$@"
        ;;
    gruvbox)
        gruvbox "$@"
        ;;
    *)
        all
esac
