#!/usr/bin/env bash

path=${1:-$(pwd)}
width=${2:-900}

echo "$path" \
    | sed -e "s@^/home/$USER@~@" \
    | sed -e 's@^/home/\([^/][^/]*\)@~\1@' \
    | sed -e 's@\(^/[^/]*/\|[^/]*/\).*\(/[^/][^/]*/[^/][^/]*/[^/][^/]*\)@\1…\2@' \
    | cut -c1-"$(echo "$width" / 3 | bc -l | sed 's/\..*//')"
