#!/usr/bin/env bash

loginctl list-users \
    | tail -n +2 \
    | head -n -2 \
    | cut -d' ' -f1 \
    | xargs -r -I{} \
        sudo -u '#{}' \
        env DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/{}/bus \
        awesome-client 'require("config.brokers").pacman:update()'
