#!/usr/bin/env bash

pacman -Qeq \
    | grep -v "$(paclist aur | sed 's/\s.*//')" \
    | grep -v "$(paclist manual | sed 's/\s.*//')" \
    > ~/.pkglist/pacman
pacman -Qeq \
    > ~/.pkglist/pacman-all
paclist aur \
    | sed 's/\s.*//' \
    > ~/.pkglist/aur
paclist manual \
    | sed 's/\s.*//' \
    > ~/.pkglist/manual
sudo pacman -Qkk \
    |& grep Modification \
    | sed -e 's/^[^/]*//' -e 's/ (.*)$//' \
    | sort \
    > ~/.pkglist/modified-files
