#!/bin/sh

if [ $# -lt 4 ]; then
    echo "Usage: $0 <merged> <base> <local> <remote>" 2>&1
    exit 1
fi

readonly MERGED=$1 BASE=$2 LOCAL=$3 REMOTE=$4
readonly TMPDIR=$(mktemp --tmpdir --directory vimmerge.XXXXXXXXXX)
trap 'rm -rf "$TMPDIR"' INT TERM EXIT

readonly THEIRS=$TMPDIR/THEIRS.${REMOTE##*.}
readonly ORIGINAL=$TMPDIR/ORIGINAL.${MERGED##*.}
cp "$MERGED" "$THEIRS"
cp "$MERGED" "$ORIGINAL"

vim -f \
    -c 'g/^<\{7} /,/^|\{7} \?\|^=\{7}\r\?$/d' \
    -c 'g/^>\{7} /d' \
    -c "w | f THEIRS | setl nomod ro | lefta vert diffs $MERGED" \
    -c 'g/^|\{7} \?\|^=\{7}\r\?$/,/^>\{7} /d' \
    -c 'g/^<\{7} /d' \
    -c "w | tabe $REMOTE | f REMOTE | setl nomod ro" \
    -c "lefta vert diffs $LOCAL | f LOCAL | setl nomod ro" \
    -c "rightb vert diffs $BASE | f BASE | setl nomod ro" \
    -c "tabe $ORIGINAL | f ORIGINAL | setl nomod ro | tabr" \
    "$THEIRS"

exit $?
