#!/bin/sh

remote=$1
location=$2
z40=0000000000000000000000000000000000000000

# filter commits that are already on the specified remote
filter_commits() {
    while IFS='' read -r commit; do
        test ! "$(git for-each-ref --contains="${commit%% *}" \
            | cut -f2 \
            | grep "^refs/remotes/$remote")" \
            && echo "$commit"
    done
    return 0
}

while IFS=' ' read -r local_ref local_sha remote_ref remote_sha; do
    if [ "$local_sha" = $z40 ]; then
        continue
    fi

    if [ "$remote_sha" = $z40 ]; then
        # new branch, examine all commits
        range="$local_sha"
    else
        # update to existing branch, examine new commits
        range="$remote_sha..$local_sha"
    fi

    # check for WIP commits
    commits=$(git log --format='%h %s' --basic-regexp -i --grep='^wip' "$range" \
        | filter_commits)
    if [ -n "$commits" ]; then
        warn1 "WIP commits detected."
        warn2 "Pass [1m--no-verify[0m to git-push to bypass this check."
        echo
        echo "$commits"
        echo
        EC=1
    fi

    # check for autosquash commits
    commits=$(git log --format='%h %s' --basic-regexp -i --grep='^fixup!\|^squash!' "$range" \
        | filter_commits)
    if [ -n "$commits" ]; then
        warn1 "Autosquash commits detected."
        warn2 "Pass [1m--no-verify[0m to git-push to bypass this check."
        echo
        echo "$commits"
        echo
        EC=2
    fi
done

exit $EC
