#!/bin/sh

DIR="$(git rev-parse --git-dir)"
mkdir "$DIR/tags_lock" 2> /dev/null || exit 0
trap 'rm -rf "$DIR/tags_lock"; rm -f "$DIR/$$.tags"' INT TERM EXIT

git ls-files --recurse-submodules \
    | ctags --tag-relative=yes -L - -f "$DIR/$$.tags"

mv "$DIR/$$.tags" "$DIR/tags"
